#cloud-config
---
users:
  - name: egi
    gecos: EGI
    primary_group: egi
    groups: users
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa
        AAAAB3NzaC1yc2EAAAADAQABAAACAQC4M/hDSYwxQd2oFY0FM1a5iaDfa66nC1WFpxC3qTtL/V5aOa2L3shDvnBxpDy/vZ/dlQe6q8Yng/T5H0wJJKnf4ty3Dur5QYl7DYhWUpb7VbY1fJjSpnWm9gnhOcB3ZVYEvn3Qw/FHDxi2B59Db0O8aYx/IbxUDJ4wcapyrsce+yK8EbTWtqtfsnioh0hDdcby/ZIiPQMBiMHGoqBH08qdy9Lj6qK65IOXukM9ByAgRVhHFZxzmG+b+VXYi45VHC0ePi66S7ocEaL85dzr+xNx5KeoQSPzGPC4iFW8VdgRGjSNUErgnNIss4NPZlq25i4gpCqhhg8KLCc/TWc1ky0ed5BzHXIEZMZigB2qvh0kMzbpWoRXJyGkPF6FmRyS2PP1Op/6rDhEBebeMnwTULOIEwuptdNPGH3oJDEXZC30kW4yYj9/Jk6tg1px6f9F6LadgrpzR/p1OzeAMF7DH+Y/DSoVLkINBXjv8rHgtsZYza9QM8Fam+PbmlOv1D5kUtsLe2aU3AduGR1Y3g6pSd4RqwTZa5kKjeNQcQMNmwbFDAUBWJLVX/rEYUpX0YfCK7RAahKvPLsgieeiYGAYdqv3H5BBeoaxH0oYRRl/JQ0yyBdDA5WxkIfiCIioNdouMC7sF1ZsJEHU1nqeZx32rstyfKTDi/v36U6Ixoee7W1xlQ==
        baptiste

packages:
  - vim

package_update: true
package_upgrade: true
package_reboot_if_required: true
